# Site settings
title: Sword and Claw
email: james@getwhiplash.com
description: > # A catalog of lifelong education.
baseurl: "/sword_and_claw" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
single_footer: 'A catalog of lifelong education'
footer_links:
    # About: ['About', '/about']
    # Writer: ['Writer 2016', '/about']
jekyll_compose:
    auto_open: true
    layout: post-no-feature

# Build settings
# markdown: kramdown
